-- MySQL Script generated by MySQL Workbench
-- Sat Nov  4 16:22:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpentTracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SpentTracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpentTracker` DEFAULT CHARACTER SET utf8 ;
USE `SpentTracker` ;

-- -----------------------------------------------------
-- Table `SpentTracker`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpentTracker`.`Categories` ;

CREATE TABLE IF NOT EXISTS `SpentTracker`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpentTracker`.`Firms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpentTracker`.`Firms` ;

CREATE TABLE IF NOT EXISTS `SpentTracker`.`Firms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpentTracker`.`Mode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpentTracker`.`Mode` ;

CREATE TABLE IF NOT EXISTS `SpentTracker`.`Mode` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpentTracker`.`People`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpentTracker`.`People` ;

CREATE TABLE IF NOT EXISTS `SpentTracker`.`People` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `iban` VARCHAR(45) NULL,
  `tel` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpentTracker`.`Spend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpentTracker`.`Spend` ;

CREATE TABLE IF NOT EXISTS `SpentTracker`.`Spend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` INT NOT NULL,
  `online` TINYINT NOT NULL,
  `date` DATE NULL,
  `Categories_id` INT NOT NULL,
  `Mode_id` INT NOT NULL,
  `Firms_id` INT NULL,
  `People_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Spend_Categories_idx` (`Categories_id` ASC),
  INDEX `fk_Spend_Firms1_idx` (`Firms_id` ASC),
  INDEX `fk_Spend_People1_idx` (`People_id` ASC),
  INDEX `fk_Spend_Mode1_idx` (`Mode_id` ASC),
  CONSTRAINT `fk_Spend_Categories`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `SpentTracker`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spend_Firms1`
    FOREIGN KEY (`Firms_id`)
    REFERENCES `SpentTracker`.`Firms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spend_People1`
    FOREIGN KEY (`People_id`)
    REFERENCES `SpentTracker`.`People` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spend_Mode1`
    FOREIGN KEY (`Mode_id`)
    REFERENCES `SpentTracker`.`Mode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SpentTracker`.`Categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `SpentTracker`;
INSERT INTO `SpentTracker`.`Categories` (`id`, `name`) VALUES (1, 'Housing');
INSERT INTO `SpentTracker`.`Categories` (`id`, `name`) VALUES (2, 'Food');

COMMIT;


-- -----------------------------------------------------
-- Data for table `SpentTracker`.`Mode`
-- -----------------------------------------------------
START TRANSACTION;
USE `SpentTracker`;
INSERT INTO `SpentTracker`.`Mode` (`id`, `name`) VALUES (1, 'credit card');
INSERT INTO `SpentTracker`.`Mode` (`id`, `name`) VALUES (2, 'cash');
INSERT INTO `SpentTracker`.`Mode` (`id`, `name`) VALUES (3, 'bank transfer');
INSERT INTO `SpentTracker`.`Mode` (`id`, `name`) VALUES (4, 'Paypal');

COMMIT;

